package cloud

import (
	"context"
	"fmt"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"

	"github.com/dbmurphy/pulumi-elasticstack/provider/pkg/provider"
)

// DeploymentPassword resets and manages the 'elastic' user password for an Elastic Cloud deployment.
type DeploymentPassword struct{}

// DeploymentPasswordInputs defines the input properties for a deployment password reset.
type DeploymentPasswordInputs struct {
	DeploymentID string `pulumi:"deploymentId"`
	RefID        string `pulumi:"refId,optional"`
}

// DeploymentPasswordState defines the output state for a deployment password reset.
type DeploymentPasswordState struct {
	DeploymentPasswordInputs

	// Outputs
	Username string `pulumi:"username"`
	Password string `pulumi:"password" provider:"secret"`
}

var (
	_ infer.CustomDiff[DeploymentPasswordInputs, DeploymentPasswordState] = (*DeploymentPassword)(nil)
	_ infer.CustomDelete[DeploymentPasswordState]                         = (*DeploymentPassword)(nil)
)

// Annotate sets resource metadata and descriptions.
func (r *DeploymentPassword) Annotate(a infer.Annotator) {
	a.Describe(r, "Resets the 'elastic' user password for an Elastic Cloud deployment. "+
		"The password is generated by the Cloud API and stored as a secret output. "+
		"Replace the resource to trigger a new password reset.")
	a.SetToken("cloud", "DeploymentPassword")
}

// Annotate sets input property descriptions and defaults.
func (i *DeploymentPasswordInputs) Annotate(a infer.Annotator) {
	a.Describe(&i.DeploymentID, "The deployment ID from Elastic Cloud.")
	a.Describe(&i.RefID, "The Elasticsearch resource ref ID. Defaults to 'main' if not specified.")
	a.SetDefault(&i.RefID, "main")
}

// Create provisions a new deployment password reset.
func (r *DeploymentPassword) Create(
	ctx context.Context,
	req infer.CreateRequest[DeploymentPasswordInputs],
) (infer.CreateResponse[DeploymentPasswordState], error) {
	cfg := infer.GetConfig[provider.Config](ctx)
	cloudClient, err := cfg.CloudClient()
	if err != nil {
		return infer.CreateResponse[DeploymentPasswordState]{}, err
	}

	path := fmt.Sprintf("/deployments/%s/elasticsearch/%s/_reset-password",
		req.Inputs.DeploymentID, req.Inputs.RefID)

	var result struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}

	if err := cloudClient.PostJSON(ctx, path, nil, &result); err != nil {
		return infer.CreateResponse[DeploymentPasswordState]{},
			fmt.Errorf("failed to reset password for deployment %s: %w",
				req.Inputs.DeploymentID, err)
	}

	id := req.Inputs.DeploymentID + "/" + req.Inputs.RefID

	return infer.CreateResponse[DeploymentPasswordState]{
		ID: id,
		Output: DeploymentPasswordState{
			DeploymentPasswordInputs: req.Inputs,
			Username:                 result.Username,
			Password:                 result.Password,
		},
	}, nil
}

// Diff computes the difference between old and new state.
func (r *DeploymentPassword) Diff(
	_ context.Context,
	req infer.DiffRequest[DeploymentPasswordInputs, DeploymentPasswordState],
) (p.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}

	if req.Inputs.DeploymentID != req.State.DeploymentID {
		diff["deploymentId"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.RefID != req.State.RefID {
		diff["refId"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}

	return p.DiffResponse{
		HasChanges:          len(diff) > 0,
		DetailedDiff:        diff,
		DeleteBeforeReplace: true,
	}, nil
}

// Delete removes the deployment password resource.
func (r *DeploymentPassword) Delete(
	_ context.Context,
	_ infer.DeleteRequest[DeploymentPasswordState],
) (infer.DeleteResponse, error) {
	// Password reset is not reversible — delete is a no-op.
	return infer.DeleteResponse{}, nil
}
