version: 2
updates:
  - package-ecosystem: gomod
    directory: /provider
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    assignees:
      - dbmurphy

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    assignees:
      - dbmurphy
